using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CSCoursework_Smiley
{
    public partial class LoginFormCreateAccount : UserControl
    {
        LoginForm parentForm;
        string[] possibleStaffNames;
        string username;
        string password;
        string securityQuestion1;
        string securityQuestion2;
        string securityQuestion3;
        string securityAnswer1;
        string securityAnswer2;
        string securityAnswer3;
        public LoginFormCreateAccount()
        {
            InitializeComponent();
        }

        public void SetParentForm(LoginForm ParentForm)
        {
            parentForm = ParentForm;
        }
        private void LoginFormCreateAccount_Load(object sender, EventArgs e)
        {
            grpBoxAccountSecurity.Location = new Point(4, 4);
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            ResetForm();
        }
        private void ResetForm()
        {
            parentForm.CancelAccountCreation();
            txtStaffName.Clear();
            txtPassword.Clear();
            txtConfirmPassword.Clear();
            lblUsername.Text = "Username (auto-generated)";
            grpBoxAccountSecurity.Visible = false;
            grpBoxAccountCreation.Visible = true;
            btnSubmit.Visible = false;
            btnNext.Visible = true;
        }
        public void UpdateTextboxAutocomplete(string[] suggestionArray)
        {
            possibleStaffNames = suggestionArray;
            AutoCompleteStringCollection autoCompleteStringCollection = new AutoCompleteStringCollection();
            autoCompleteStringCollection.AddRange(suggestionArray);
            txtStaffName.AutoCompleteCustomSource = autoCompleteStringCollection;
            txtStaffName.AutoCompleteMode = AutoCompleteMode.Suggest;
            txtStaffName.AutoCompleteSource = AutoCompleteSource.CustomSource;
        }

        private void txtStaffName_TextChanged(object sender, EventArgs e)
        {
            if (possibleStaffNames.Contains<string>(txtStaffName.Text))
            {
                username = $"{txtStaffName.Text.ToLower().Split(' ')[0][0]}{txtStaffName.Text.ToLower().Split(' ')[1]}";
                lblUsername.Text = $"Username ({username})";
            }
        }

        private void btnNext_Click(object sender, EventArgs e)
        {
            if (lblUsername.Text == "Username (auto-generated)")
            {
                MessageBox.Show("You must provde your name in order for a username to be autogenerated.");
                return;
            }
            // Password length check
            if (txtPassword.Text.Length < 8)
            {
                MessageBox.Show("Your password must contain at least 8 characters.");
                return;
            }
            bool passwordContainsLetter = false;
            bool passwordContainsCaptial = false;
            bool passwordContainsInteger = false;
            foreach (char letter in txtPassword.Text)
            {
                if (letter == ' ')
                {
                    MessageBox.Show("Password Cannot contain any spaces.");
                    return;
                }
                if (Char.IsLetter(letter))
                {
                    passwordContainsLetter = true;
                    if (Char.IsUpper(letter))
                    {
                        passwordContainsCaptial = true;
                    }
                }
                else
                {
                    passwordContainsInteger = true;
                }
            }

            // Character/Type checks
            if (!passwordContainsLetter)
            {
                MessageBox.Show("Password must contain a letter.");
                return;
            }
            if (!passwordContainsCaptial)
            {
                MessageBox.Show("Password must contain a captial letter.");
                return;
            }
            if (!passwordContainsInteger)
            {
                MessageBox.Show("Password must contain a number.");
                return;
            }

            if (txtPassword.Text != txtConfirmPassword.Text)
            {
                MessageBox.Show("Passwords do not match. Try entering them again.");
                return;
            }

            password = txtPassword.Text;
            grpBoxAccountCreation.Visible = false;
            btnNext.Visible = false;
            grpBoxAccountSecurity.Visible = true;
            btnSubmit.Visible = true;
            //MD5 encryption to store the password.
        }

        private void btnSubmit_Click(object sender, EventArgs e)
        {
            if (comboBoxSecurityQuestion1.SelectedItem == comboBoxSecurityQuestion2.SelectedItem || comboBoxSecurityQuestion1.SelectedItem == comboBoxSecurityQuestion3.SelectedItem || comboBoxSecurityQuestion2.SelectedItem == comboBoxSecurityQuestion3.SelectedItem)
            {
                MessageBox.Show("You cannot use the same security question more than once.");
                return;
            }
            if (txtSecurityAnswer1.Text.Trim() == "")
            {
                MessageBox.Show("You must provide answers to all security questions. Check answer 1.");
                return;
            }
            if (txtSecurityAnswer2.Text.Trim() == "")
            {
                MessageBox.Show("You must provide answers to all security questions. Check answer 2.");
                return;
            }
            if (txtSecurityAnswer3.Text.Trim() == "")
            {
                MessageBox.Show("You must provide answers to all security questions. Check answer 3.");
                return;
            }

            securityQuestion1 = comboBoxSecurityQuestion1.SelectedItem.ToString();
            securityQuestion2 = comboBoxSecurityQuestion2.SelectedItem.ToString();
            securityQuestion3 = comboBoxSecurityQuestion3.SelectedItem.ToString();
            securityAnswer1 = txtSecurityAnswer1.Text;
            securityAnswer2 = txtSecurityAnswer2.Text;
            securityAnswer3 = txtSecurityAnswer3.Text;
            parentForm.SaveAccount(username, password, securityQuestion1, securityAnswer1, securityQuestion2, securityAnswer2, securityQuestion3, securityAnswer3);
            ResetForm();
            MessageBox.Show("Account Successfully Created.");
        }
    }
}
